[Settings]
; Set windows version: 11 or 10.
WindowsVersion=11

; This is the position where the tray will be moved.
TrayMoveX=500
TrayMoveY=50

; --------------------------------------------------------------
; ^ is Ctrl | >^ is RCtrl | <^ is LCtrl | ! is Alt | >! is RAlt
; <! is LAlt | <^>! is LCtrl & RAlt | # is Win | + is Shift
; --------------------------------------------------------------
; Hotkey to summon the tray at your willing (after clicking the button once to launch the script).
; Default: Alt + S
SummonHotkey=!s
; Hotkey to manually close the summoned tray.
; Default: Alt + C
HideHotkey=!c

; Up to how long (in seconds) should the script wait for the overflow tray window to appear?
TrayWinWait=4

; Release delay (in milliseconds) between Win+B and Enter.
ShortcutWait=50